id: P004207
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG6187
  title: མན་ངག་ལྷན་ཐབས་ཀྱི་བརྡ་བཀྲོལ་རྣམ་རྒྱལ་གསེར་མདོག་གི་ཕྲེང་བ།
  author: ''
  volumes:
    e0a13cf4d40341eaac3cb1830fe37d71:
      image_group_id: I1KG6219
      title: ''
      volume_number: 1
      total_pages: 238
      base_file: v001.txt
