id: P004207
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 11:01:07.573683
source_metadata:
  id: bdr:W1KG6187
  title: མན་ངག་ལྷན་ཐབས་ཀྱི་བརྡ་བཀྲོལ་རྣམ་རྒྱལ་གསེར་མདོག་གི་ཕྲེང་བ།
  author: ''
  volumes:
    e0a13cf4d40341eaac3cb1830fe37d71:
      image_group_id: I1KG6219
      title: ''
      volume_number: 1
      total_pages: 238
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
